//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarshaBank.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HarshaBank.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        internal static string AccountsMenu_Items_AddAccount {
            get {
                return ResourceManager.GetString("AccountsMenu_Items_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string AccountsMenu_Items_DeleteAccount {
            get {
                return ResourceManager.GetString("AccountsMenu_Items_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Menu.
        /// </summary>
        internal static string AccountsMenu_Items_Exit {
            get {
                return ResourceManager.GetString("AccountsMenu_Items_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Account.
        /// </summary>
        internal static string AccountsMenu_Items_UpdateAccount {
            get {
                return ResourceManager.GetString("AccountsMenu_Items_UpdateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Accounts.
        /// </summary>
        internal static string AccountsMenu_Items_ViewAccounts {
            get {
                return ResourceManager.GetString("AccountsMenu_Items_ViewAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string AccountsMenu_Title {
            get {
                return ResourceManager.GetString("AccountsMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account statement cancelled - end date is before start date.
        /// </summary>
        internal static string AccountStatement_Errors_EndDateBeforeStartDate {
            get {
                return ResourceManager.GetString("AccountStatement_Errors_EndDateBeforeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account statement cancelled.
        /// </summary>
        internal static string AccountStatement_Notifications_Cancelled {
            get {
                return ResourceManager.GetString("AccountStatement_Notifications_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date (yyyy-mm-dd) [{0:yyyy-MM-dd}].
        /// </summary>
        internal static string AccountStatement_Prompts_EndDate {
            get {
                return ResourceManager.GetString("AccountStatement_Prompts_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date (yyyy-mm-dd) [{0:yyyy-MM-dd}].
        /// </summary>
        internal static string AccountStatement_Prompts_StartDate {
            get {
                return ResourceManager.GetString("AccountStatement_Prompts_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE         CREDITS         DEBITS          BALANCE         DESCRIPTION
        ///----------   -------------   -------------   -------------   -----------.
        /// </summary>
        internal static string AccountStatement_Statement_Header {
            get {
                return ResourceManager.GetString("AccountStatement_Statement_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:yyyy-MM-dd}   {1}   {2}   {3}   {4}.
        /// </summary>
        internal static string AccountStatement_Statement_Item {
            get {
                return ResourceManager.GetString("AccountStatement_Statement_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                              {0,13:F2}   Starting balance.
        /// </summary>
        internal static string AccountStatement_Statement_Item_StartingBalance {
            get {
                return ResourceManager.GetString("AccountStatement_Statement_Item_StartingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transactions were made during the specified time period
        ///.
        /// </summary>
        internal static string AccountStatement_Statement_NoMatches {
            get {
                return ResourceManager.GetString("AccountStatement_Statement_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Transactions for account {0} ({1}) from {2:yyyy-MM-dd} to {3:yyyy-MM-dd}
        ///.
        /// </summary>
        internal static string AccountStatement_Statement_Title {
            get {
                return ResourceManager.GetString("AccountStatement_Statement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Statement.
        /// </summary>
        internal static string AccountStatement_Title {
            get {
                return ResourceManager.GetString("AccountStatement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account Code: {0}
        ///Account Added.
        /// </summary>
        internal static string AddAccount_Notifications_Added {
            get {
                return ResourceManager.GetString("AddAccount_Notifications_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation cancelled.
        /// </summary>
        internal static string AddAccount_Notifications_Cancelled {
            get {
                return ResourceManager.GetString("AddAccount_Notifications_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        internal static string AddAccount_Title {
            get {
                return ResourceManager.GetString("AddAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer Code: {0}
        ///Customer Added.
        /// </summary>
        internal static string AddCustomer_Notifications_Added {
            get {
                return ResourceManager.GetString("AddCustomer_Notifications_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer creation cancelled.
        /// </summary>
        internal static string AddCustomer_Notifications_Cancelled {
            get {
                return ResourceManager.GetString("AddCustomer_Notifications_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        internal static string AddCustomer_Title {
            get {
                return ResourceManager.GetString("AddCustomer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data File Path (enter a space to clear this setting).
        /// </summary>
        internal static string ApplicationConfiguration_Label_DataFilePath {
            get {
                return ResourceManager.GetString("ApplicationConfiguration_Label_DataFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration cancelled.
        /// </summary>
        internal static string Configuration_Notifications_Cancelled {
            get {
                return ResourceManager.GetString("Configuration_Notifications_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration was updated.
        /// </summary>
        internal static string Configuration_Notifications_Updated {
            get {
                return ResourceManager.GetString("Configuration_Notifications_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will re-load application data - are you sure (yes or no)?.
        /// </summary>
        internal static string Configuration_Prompts_Confirm {
            get {
                return ResourceManager.GetString("Configuration_Prompts_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration_Title {
            get {
                return ResourceManager.GetString("Configuration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        internal static string CustomersMenu_Items_AddCustomer {
            get {
                return ResourceManager.GetString("CustomersMenu_Items_AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer.
        /// </summary>
        internal static string CustomersMenu_Items_DeleteCustomer {
            get {
                return ResourceManager.GetString("CustomersMenu_Items_DeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Menu.
        /// </summary>
        internal static string CustomersMenu_Items_Exit {
            get {
                return ResourceManager.GetString("CustomersMenu_Items_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Customers.
        /// </summary>
        internal static string CustomersMenu_Items_SearchCustomers {
            get {
                return ResourceManager.GetString("CustomersMenu_Items_SearchCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer.
        /// </summary>
        internal static string CustomersMenu_Items_UpdateCustomer {
            get {
                return ResourceManager.GetString("CustomersMenu_Items_UpdateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Customers.
        /// </summary>
        internal static string CustomersMenu_Items_ViewCustomers {
            get {
                return ResourceManager.GetString("CustomersMenu_Items_ViewCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string CustomersMenu_Title {
            get {
                return ResourceManager.GetString("CustomersMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete account with non-zero balance.
        /// </summary>
        internal static string DeleteAccount_Errors_NonZeroBalance {
            get {
                return ResourceManager.GetString("DeleteAccount_Errors_NonZeroBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified account does not exist.
        /// </summary>
        internal static string DeleteAccount_Errors_NotFound {
            get {
                return ResourceManager.GetString("DeleteAccount_Errors_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deletion cancelled.
        /// </summary>
        internal static string DeleteAccount_Notifications_Cancelled {
            get {
                return ResourceManager.GetString("DeleteAccount_Notifications_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was deleted.
        /// </summary>
        internal static string DeleteAccount_Notifications_Deleted {
            get {
                return ResourceManager.GetString("DeleteAccount_Notifications_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account {0} ({1}) - yes or no?.
        /// </summary>
        internal static string DeleteAccount_Prompts_Confirm {
            get {
                return ResourceManager.GetString("DeleteAccount_Prompts_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string DeleteAccount_Title {
            get {
                return ResourceManager.GetString("DeleteAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete customer with active accounts.
        /// </summary>
        internal static string DeleteCustomer_Errors_ActiveAccounts {
            get {
                return ResourceManager.GetString("DeleteCustomer_Errors_ActiveAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified customer does not exist.
        /// </summary>
        internal static string DeleteCustomer_Errors_NotFound {
            get {
                return ResourceManager.GetString("DeleteCustomer_Errors_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer deletion cancelled.
        /// </summary>
        internal static string DeleteCustomer_Notifications_Cancelled {
            get {
                return ResourceManager.GetString("DeleteCustomer_Notifications_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer was deleted.
        /// </summary>
        internal static string DeleteCustomer_Notifications_Deleted {
            get {
                return ResourceManager.GetString("DeleteCustomer_Notifications_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete customer {0} ({1}) - yes or no?.
        /// </summary>
        internal static string DeleteCustomer_Prompts_Confirm {
            get {
                return ResourceManager.GetString("DeleteCustomer_Prompts_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer.
        /// </summary>
        internal static string DeleteCustomer_Title {
            get {
                return ResourceManager.GetString("DeleteCustomer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date.
        /// </summary>
        internal static string Dialog_Errors_InvalidDate {
            get {
                return ResourceManager.GetString("Dialog_Errors_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered saving application data: {0}.
        /// </summary>
        internal static string Exit_Errors_Save {
            get {
                return ResourceManager.GetString("Exit_Errors_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! Visit again..
        /// </summary>
        internal static string Exit_Notifications_Exit {
            get {
                return ResourceManager.GetString("Exit_Notifications_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a {0}.
        /// </summary>
        internal static string FormControl_Errors_TypeConversion {
            get {
                return ResourceManager.GetString("FormControl_Errors_TypeConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds in source account.
        /// </summary>
        internal static string FundsTransfer_Errors_InsufficientFunds {
            get {
                return ResourceManager.GetString("FundsTransfer_Errors_InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be a positive value with no more than two decimal places.
        /// </summary>
        internal static string FundsTransfer_Errors_InvalidAmount {
            get {
                return ResourceManager.GetString("FundsTransfer_Errors_InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds transfer cancelled - destination account must be different from the source account.
        /// </summary>
        internal static string FundsTransfer_Errors_SourceAccountIsAlsoDestinationAccount {
            get {
                return ResourceManager.GetString("FundsTransfer_Errors_SourceAccountIsAlsoDestinationAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds transfer cancelled.
        /// </summary>
        internal static string FundsTransfer_Notifications_Cancelled {
            get {
                return ResourceManager.GetString("FundsTransfer_Notifications_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds transferred:
        ///
        ///{0} ({1}):
        ///    {2} ({3}):
        ///        Old: {4:F2}
        ///        New: {5:F2}
        ///
        ///{6} ({7}):
        ///    {8} ({9}):
        ///        Old: {10:F2}
        ///        New: {11:F2}.
        /// </summary>
        internal static string FundsTransfer_Notifications_Transferred {
            get {
                return ResourceManager.GetString("FundsTransfer_Notifications_Transferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount ({0:F2} available).
        /// </summary>
        internal static string FundsTransfer_Prompts_Amount {
            get {
                return ResourceManager.GetString("FundsTransfer_Prompts_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Transfer {0:F2} - yes or no?.
        /// </summary>
        internal static string FundsTransfer_Prompts_Confirm {
            get {
                return ResourceManager.GetString("FundsTransfer_Prompts_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string FundsTransfer_Prompts_Description {
            get {
                return ResourceManager.GetString("FundsTransfer_Prompts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Account:.
        /// </summary>
        internal static string FundsTransfer_Prompts_DestinationAccount {
            get {
                return ResourceManager.GetString("FundsTransfer_Prompts_DestinationAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Account:.
        /// </summary>
        internal static string FundsTransfer_Prompts_SourceAccount {
            get {
                return ResourceManager.GetString("FundsTransfer_Prompts_SourceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds Transfer.
        /// </summary>
        internal static string FundsTransfer_Title {
            get {
                return ResourceManager.GetString("FundsTransfer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds transfer statement cancelled - end date is before start date.
        /// </summary>
        internal static string FundsTransferStatement_Errors_EndDateBeforeStartDate {
            get {
                return ResourceManager.GetString("FundsTransferStatement_Errors_EndDateBeforeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds transfer statement cancelled.
        /// </summary>
        internal static string FundsTransferStatement_Notifications_Cancelled {
            get {
                return ResourceManager.GetString("FundsTransferStatement_Notifications_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date (yyyy-mm-dd) [{0:yyyy-MM-dd}].
        /// </summary>
        internal static string FundsTransferStatement_Prompts_EndDate {
            get {
                return ResourceManager.GetString("FundsTransferStatement_Prompts_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date (yyyy-mm-dd) [{0:yyyy-MM-dd}].
        /// </summary>
        internal static string FundsTransferStatement_Prompts_StartDate {
            get {
                return ResourceManager.GetString("FundsTransferStatement_Prompts_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE         SOURCE CUSTOMER/ACCOUNT                    DESTINATION CUSTOMER/ACCOUNT               AMOUNT
        ///----------   ----------------------------------------   ----------------------------------------   -------------.
        /// </summary>
        internal static string FundsTransferStatement_Statement_Header {
            get {
                return ResourceManager.GetString("FundsTransferStatement_Statement_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:yyyy-MM-dd}   {1}   {2}   {3,13:F2}
        ///             {4}   {5}
        ///.
        /// </summary>
        internal static string FundsTransferStatement_Statement_Item {
            get {
                return ResourceManager.GetString("FundsTransferStatement_Statement_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string FundsTransferStatement_Statement_Item_Actor {
            get {
                return ResourceManager.GetString("FundsTransferStatement_Statement_Item_Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transactions were made during the specified time period
        ///.
        /// </summary>
        internal static string FundsTransferStatement_Statement_NoMatches {
            get {
                return ResourceManager.GetString("FundsTransferStatement_Statement_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Transactions from {0:yyyy-MM-dd} to {1:yyyy-MM-dd}
        ///.
        /// </summary>
        internal static string FundsTransferStatement_Statement_Title {
            get {
                return ResourceManager.GetString("FundsTransferStatement_Statement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...).
        /// </summary>
        internal static string FundsTransferStatement_Statement_TruncationIndicator {
            get {
                return ResourceManager.GetString("FundsTransferStatement_Statement_TruncationIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds Transfer Statement.
        /// </summary>
        internal static string FundsTransferStatement_Title {
            get {
                return ResourceManager.GetString("FundsTransferStatement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string Login_Notifications_CredentialsRejected {
            get {
                return ResourceManager.GetString("Login_Notifications_CredentialsRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Prompts_Password {
            get {
                return ResourceManager.GetString("Login_Prompts_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string Login_Prompts_UserName {
            get {
                return ResourceManager.GetString("Login_Prompts_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Page.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string MainMenu_Items_Accounts {
            get {
                return ResourceManager.GetString("MainMenu_Items_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Statement.
        /// </summary>
        internal static string MainMenu_Items_AccountStatement {
            get {
                return ResourceManager.GetString("MainMenu_Items_AccountStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string MainMenu_Items_Configuration {
            get {
                return ResourceManager.GetString("MainMenu_Items_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string MainMenu_Items_Customers {
            get {
                return ResourceManager.GetString("MainMenu_Items_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainMenu_Items_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Items_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds Transfer.
        /// </summary>
        internal static string MainMenu_Items_FundsTransfer {
            get {
                return ResourceManager.GetString("MainMenu_Items_FundsTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds Transfer Statement.
        /// </summary>
        internal static string MainMenu_Items_FundsTransferStatement {
            get {
                return ResourceManager.GetString("MainMenu_Items_FundsTransferStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string MainMenu_Title {
            get {
                return ResourceManager.GetString("MainMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid choice - please try again..
        /// </summary>
        internal static string MenuControl_Errors_InvalidChoice {
            get {
                return ResourceManager.GetString("MenuControl_Errors_InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter choice.
        /// </summary>
        internal static string MenuControl_Prompts_Choice {
            get {
                return ResourceManager.GetString("MenuControl_Prompts_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer search cancelled.
        /// </summary>
        internal static string SearchCustomers_Notifications_Cancelled {
            get {
                return ResourceManager.GetString("SearchCustomers_Notifications_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching customers were found.
        /// </summary>
        internal static string SearchCustomers_Notifications_NoMatches {
            get {
                return ResourceManager.GetString("SearchCustomers_Notifications_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Term.
        /// </summary>
        internal static string SearchCustomers_Prompts_SearchTerm {
            get {
                return ResourceManager.GetString("SearchCustomers_Prompts_SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Customers.
        /// </summary>
        internal static string SearchCustomers_Title {
            get {
                return ResourceManager.GetString("SearchCustomers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified account was not found.
        /// </summary>
        internal static string SelectAccount_Errors_NotFound {
            get {
                return ResourceManager.GetString("SelectAccount_Errors_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching accounts were found.
        /// </summary>
        internal static string SelectAccount_Notifications_NoMatches {
            get {
                return ResourceManager.GetString("SelectAccount_Notifications_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account: {0} ({1}).
        /// </summary>
        internal static string SelectAccount_Notifications_Selected {
            get {
                return ResourceManager.GetString("SelectAccount_Notifications_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code or Search Term (prefix with &quot;c:&quot; to search by customer).
        /// </summary>
        internal static string SelectAccount_Prompts_SearchTerm {
            get {
                return ResourceManager.GetString("SelectAccount_Prompts_SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Account.
        /// </summary>
        internal static string SelectAccount_Title {
            get {
                return ResourceManager.GetString("SelectAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid choice - please try again.
        /// </summary>
        internal static string SelectControl_Errors_InvalidChoice {
            get {
                return ResourceManager.GetString("SelectControl_Errors_InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///******** {0}page {1} / {2} ********
        ///.
        /// </summary>
        internal static string SelectControl_Headers_Page {
            get {
                return ResourceManager.GetString("SelectControl_Headers_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string SelectControl_Menu_Exit {
            get {
                return ResourceManager.GetString("SelectControl_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        internal static string SelectControl_Menu_NextPage {
            get {
                return ResourceManager.GetString("SelectControl_Menu_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        internal static string SelectControl_Menu_PreviousPage {
            get {
                return ResourceManager.GetString("SelectControl_Menu_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter choice.
        /// </summary>
        internal static string SelectControl_Prompts_Choice {
            get {
                return ResourceManager.GetString("SelectControl_Prompts_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified customer does not exist.
        /// </summary>
        internal static string SelectCustomer_Errors_NotFound {
            get {
                return ResourceManager.GetString("SelectCustomer_Errors_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching customers were found.
        /// </summary>
        internal static string SelectCustomer_Notifications_NoMatches {
            get {
                return ResourceManager.GetString("SelectCustomer_Notifications_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer: {0} ({1}).
        /// </summary>
        internal static string SelectCustomer_Notifications_Selected {
            get {
                return ResourceManager.GetString("SelectCustomer_Notifications_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code or Search Term.
        /// </summary>
        internal static string SelectCustomer_Prompts_SearchTerm {
            get {
                return ResourceManager.GetString("SelectCustomer_Prompts_SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Customer.
        /// </summary>
        internal static string SelectCustomer_Title {
            get {
                return ResourceManager.GetString("SelectCustomer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered loading application data: {0}.
        /// </summary>
        internal static string Startup_Errors_Load {
            get {
                return ResourceManager.GetString("Startup_Errors_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harsha Bank.
        /// </summary>
        internal static string Startup_Title {
            get {
                return ResourceManager.GetString("Startup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified account does not exist.
        /// </summary>
        internal static string UpdateAccount_Errors_NotFound {
            get {
                return ResourceManager.GetString("UpdateAccount_Errors_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account update cancelled.
        /// </summary>
        internal static string UpdateAccount_Notifications_Cancelled {
            get {
                return ResourceManager.GetString("UpdateAccount_Notifications_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was updated.
        /// </summary>
        internal static string UpdateAccount_Notifications_Updated {
            get {
                return ResourceManager.GetString("UpdateAccount_Notifications_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Account.
        /// </summary>
        internal static string UpdateAccount_Title {
            get {
                return ResourceManager.GetString("UpdateAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified customer does not exist.
        /// </summary>
        internal static string UpdateCustomer_Errors_NotFound {
            get {
                return ResourceManager.GetString("UpdateCustomer_Errors_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer update cancelled.
        /// </summary>
        internal static string UpdateCustomer_Notifications_Cancelled {
            get {
                return ResourceManager.GetString("UpdateCustomer_Notifications_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer was updated.
        /// </summary>
        internal static string UpdateCustomer_Notifications_Updated {
            get {
                return ResourceManager.GetString("UpdateCustomer_Notifications_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer.
        /// </summary>
        internal static string UpdateCustomer_Title {
            get {
                return ResourceManager.GetString("UpdateCustomer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no active accounts.
        /// </summary>
        internal static string ViewAccounts_Notifications_NoMatches {
            get {
                return ResourceManager.GetString("ViewAccounts_Notifications_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Accounts.
        /// </summary>
        internal static string ViewAccounts_Title {
            get {
                return ResourceManager.GetString("ViewAccounts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no active customers.
        /// </summary>
        internal static string ViewCustomers_Notifications_NoMatches {
            get {
                return ResourceManager.GetString("ViewCustomers_Notifications_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Customers.
        /// </summary>
        internal static string ViewCustomers_Title {
            get {
                return ResourceManager.GetString("ViewCustomers_Title", resourceCulture);
            }
        }
    }
}
